---
language: ruby
rvm:
- 2.5.5
- 2.6.3
- 2.7.2
before_install:
- rvm use @global
- gem uninstall bundler -x || true
- gem install bundler --force --version=1.17.3
- bundler --version
- "./bin/setup"
script:
- bundle exec rake spec
- bundle exec rubocop --fail-level C
gemfile:
- gemfiles/rails_5.2.6_activeadmin_2.9.0_reform_2.6.0_reform_rails_0.2.3_bootsnap_1.8.1.gemfile
- gemfiles/rails_6.1.4.1_activeadmin_2.9.0_reform_2.6.0_reform_rails_0.2.3_bootsnap_1.8.1.gemfile
addons:
  code_climate:
    repo_token: c326cca5984d0e32d2c6b5d9b985756ee9312f63fc6a9480fc9cfa55c454d68a
